version: "3"

services:
  aglio:
    container_name: api-documents
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../api-blueprint:/app"
    tty: true
    command: aglio -i index.md -s -h 0.0.0.0
